overrides:
  ceph:
    conf:
      client:
        fuse default permissions: false
        client acl type: posix_acl
tasks:
- workunit:
    timeout: 3h
    clients:
      all:
        - fs/misc/acl.sh
        - fs/misc/chmod.sh
