# pjd suite is a serial metadata operation correctness suite. It doesn't
# generate a metadata tree that triggers metadata balancing.
teuthology:
  postmerge:
    - if yaml.overrides.ceph.cephfs.max_mds > 1 then reject() end
overrides:
  ceph:
    conf:
      client:
        fuse set user groups: true
        fuse default permissions: false
tasks:
- workunit:
    timeout: 6h
    clients:
      all:
        - suites/pjd.sh
