tasks:
- ceph:
    cluster-conf:
      global:
        auth service cipher: aes
        debug auth: 30
        auth mon ticket ttl: 30
        auth service ticket ttl: 30
      mon:
        mon auth allow insecure key: true
    cephx:
      key_type: aes
