tasks:
- exec:
    mon.a:
      - ceph config dump
      - ceph auth ls
- ceph.key_rotate:
    daemons: [mgr.*, osd.*, mds.*]
    key_type: aes256k
- exec:
    mon.a:
      - ceph auth ls
      - ceph config set global auth_service_cipher aes256k
