overrides:
  ceph:
    log-ignorelist:
    - POOL_APP_NOT_ENABLED
    - do not have an application enabled
tasks:
- exec:
   client.0:
   - ceph_test_libcephsqlite
- workunit:
   clients:
     client.0:
     - rados/test_libcephsqlite.sh foo
