overrides:
  ceph-fuse:
    disabled: true
  kclient:
    disabled: true
tasks:
- check-counter:
    counters:
      mds:
        - "mds.dir_split"
- workunit:
    timeout: 3h
    clients:
      client.0:
        - libcephfs/test.sh
