overrides:
  ceph:
    conf:
      mgr:
        debug_mgr: 20
        debug_ms: 1
        debug_finisher: 20
    log-whitelist:
      - OSD full dropping all updates
      - OSD near full
      - pausewr flag
      - failsafe engaged, dropping updates
      - failsafe disengaged, no longer dropping
      - is full \(reached quota
      - POOL_FULL
      - POOL_BACKFILLFULL

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_snap_schedules
