overrides:
  ceph:
    conf:
      client:
        fuse set user groups: true
        fuse default permissions: false
tasks:
- workunit:
    timeout: 3h
    clients:
      all:
        - suites/pjd.sh
